title: Jeffrey Chen
description: Materials, Photoreactors, Prototypes, Photography & Notes
theme: minima

header_pages:
  - about.md
  - professional-work.md
  - personal-projects.md
  - photography.md
  - writing.md
  - cv.md
  - contact.md
