title: Jeffrey Chen, Ph.D.
description: Materials, Advanced Characterization, Functional Design, Prototypes, Photography & Notes
theme: minima

header_pages:
  - about.md
  - professional-work.md
  - personal-projects.md
  - art.md
  - cv.md
  - contact.md
